server:
  port: 8089

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://18.217.253.149:5432/db_energy_dev}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:agade123}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: "/api/v1/"